spring:
  redis:
    port: 6379
    host: 127.0.0.1
  application:
    name: weather-micro-sync
  zipkin:
    base-url: http://localhost:8085
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://EurekaServer:8761/eureka/
server:
  port: 8082